### ISSUE TITLE
Add Raw Binary Exporter and Importer (.BIN)

### ISSUE THREAD

**Issue by TheRealHamtaro126** [drdnar/MFE#1]
Hi, I would like to suggest a 1 bit Raw Binary (.BIN) Exporter and Importer:

-Specify height size and width type of font:
-0-255 Nx8 font format, (single width), or...
-0-255 Nx16 font format (double width), and...
-Also, a way to convert between the two formats would be a helpful bonus...

**Comment by drdnar** [comment]
I don't understand exactly what such a format would look like. Like the FixedWidthCEFontExporter format, but in binary instead of assembly source and without the header?

**Comment by TheRealHamtaro126** [comment]
There is a choice for the height for the font with either 8 or 16 pixels width window, in Binary (.BIN) form

They are already assembled without header, in other words...

the 16 pixels width window with is for DOS 40-Column Mode simulation, in which fonts use 2 pixels instead of 1 pixel.

**Comment by drdnar** [comment]
So, if you were to generate the output .bin file using assembly, the assembly source file would look like:
```
; 8-pixel-wide font
    ; Char 0
    .db char0_line0
    .db char0_line1
    . . .
    .db char1_line0
    . . .
    .db char255_lineN

; 16-pixel-wide font, with big-endian byte order
    ; Char 0
    .dw char0_line0
    .dw char0_line1
    . . .
    .dw char1_line0
    . . .
    .dw char255_lineN
```
(This is so I know exactly how to format the data.)

**Comment by TheRealHamtaro126** [comment]
Yep, That is the format I'm talking about here. but we need to choose the height before export or import.

**Comment by drdnar** [comment]
Wouldn't height be implied by the font settings?

**Comment by TheRealHamtaro126** [comment]
Yes, That would be correct. but the format is in it's assembled binary form only, and is not an executable font like .FNT or .TTF, or source like .ASM or .C, and cannot be determined unless manually input by a human.

**Comment by drdnar** [comment]
Weeell this took a lot longer than it should have given the simplicity of the request.
